SELECT 
    *
FROM
    cleaned_sales
LIMIT 10;

-- QUES 1. What is the total revenue generated by male vs female customers ?

SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    cleaned_sales
GROUP BY gender;

-- QUES 2. Which customer used a discount but still spent more than average purchase account ?

SELECT 
    customer_id, purchase_amount
FROM
    cleaned_sales
WHERE
    discount_applied = 'yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            cleaned_sales);

-- QUES 3. Which are the top 5 products with the highest average review rating ?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS 'Average Review Rating'
FROM
    cleaned_sales
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- QUES 4. Compare the average purchase amounts between standard and express shipping ?

SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS 'Average Purchase Amount'
FROM
    cleaned_sales
WHERE
    shipping_type IN ('Express' , 'Standard')
GROUP BY shipping_type;

-- QUES 5. Do subscribed customers spend more? Compare average spent and total revenue between subscribers and non-subscribers ?

SELECT 
    subscription_status,
    AVG(purchase_amount) AS 'Average Purchase Amount',
    COUNT(customer_id) AS 'Total Customers',
    SUM(purchase_amount) AS 'Total Revenue'
FROM
    cleaned_sales
GROUP BY subscription_status;

-- QUES 6. Which 5 products have the highest percentage of purchases with discount applied ?

SELECT 
    item_purchased,
    ROUND(SUM(CASE
                WHEN discount_applied = 'yes' THEN 1
                ELSE 0
            END) / COUNT(*) * 100,
            2) AS discount_rate
FROM
    cleaned_sales
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- QUES 7. Segment customers into new, returning and loyal based on their total number of previous purchases and show the count of each segment ?

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM cleaned_sales
)
SELECT
    customer_segment,
    COUNT(*) AS "Number Of Customers"
FROM customer_type
GROUP BY customer_segment;

-- QUES 8. What are top 3 most purchased products in each category?

with item_count as ( select category, item_purchased, count(customer_id) as total_orders, row_number() over (partition by category order by count(customer_id) desc) as item_rank from cleaned_sales group by category, item_purchased)
select item_rank, category, item_purchased, total_orders from item_count where item_rank <=3;

-- QUES 9. Are customers who are repeat buyers also likely to subscribe ?

SELECT 
    subscription_status, COUNT(customer_id) AS 'Repeat Buyers'
FROM
    cleaned_sales
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- QUES 10. What is the revenue contribution of each age group ?

SELECT 
    age_group, SUM(purchase_amount) AS total_revenue
FROM
    cleaned_sales
GROUP BY age_group
ORDER BY total_revenue DESC;